# Generated by Django 3.2.11 on 2024-05-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='thing',
        ),
        migrations.AddField(
            model_name='order',
            name='things',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
