# Generated by Django 3.2.11 on 2024-05-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240509_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCar',
        ),
    ]
